version: '3.8'

services:
  app:
    build: .
    container_name: task_manager_app
    depends_on:
      - db
      - redis
      - rabbitmq
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/postgres
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/

  migrations:
    build: .
    container_name: task_manager_migrations
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/postgres
    entrypoint: ["sh", "-c", "alembic upgrade head"]

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: mmurad
      POSTGRES_PASSWORD: Manapov001
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: task_manager_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: task_manager_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"